[theme]
base = "dark"

primaryColor = "#1DB954"          # Spotify green
backgroundColor = "#121212"       # Spotify dark background
secondaryBackgroundColor = "#181818"
textColor = "#FFFFFF"

font = "sans serif"
